name: Build sys-tweak

on:
  workflow_dispatch:
  repository_dispatch:
    types: [push]
    repositories:
      p-sam/switch-sys-tweak

permissions:
  contents: write

jobs:
  container-build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64
    steps:
      - name: env
        run: |
          cat /proc/cpuinfo
          free -m

      - name: Checkout sys-tweak repository
        uses: actions/checkout@v2
        with:
          repository: p-sam/switch-sys-tweak
          ref: develop
          submodules: recursive
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global --add safe.directory /__w/switch-sys-tweak/switch-sys-tweak

      - name: Install deps - libnx
        run: |
          git clone https://github.com/switchbrew/libnx.git /tmp/libnx
          make -C /tmp/libnx install -j4

      - name: Install deps - ams libs
        run: |
          make -C lib/ams/libstratosphere -j4

      - name: Build sys-tweak
        run: |
          make clean
          make FEAT_NSRO_CONTROL="Y" FEAT_NSAM_CONTROL="Y" -j4

      - name: Package sys-tweak.nsp in .zip file
        run: |
          mkdir -p out/atmosphere/contents/00FF747765616BFF/
          cp out/sys-tweak.nsp out/atmosphere/contents/00FF747765616BFF/exefs.nsp
          echo '{\n  "name": "sys-tweak",\n  "tid": "00FF747765616BFF",\n  "requires_reboot": true\n}' > out/atmosphere/contents/00FF747765616BFF/toolbox.json
          mkdir -p out/atmosphere/contents/00FF747765616BFF/flags
          touch out/atmosphere/contents/00FF747765616BFF/flags/boot2.flag
          cd out && zip -r sys-tweak.zip atmosphere/

      - name: Set env variables for release
        id: commit_info
        run: |
          echo "CURRENT_DATE=$(date +%Y%m%d%M)" >> $GITHUB_ENV
          COMMIT_SHA=$(git rev-parse HEAD)
          echo "sha=$COMMIT_SHA" >> $GITHUB_OUTPUT

      - name: Create release and upload files
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.CURRENT_DATE }}
          body: |
            Automatically generated from latest [p-sam/switch-sys-tweak](https://github.com/p-sam/switch-sys-tweak/) commit.
            Commit details: [${{ steps.commit_info.outputs.sha }}](https://github.com/p-sam/switch-sys-tweak/commit/${{ steps.commit_info.outputs.sha }})
          release_name: Release ${{ env.CURRENT_DATE }}
          file_glob: true
          file: out/sys-tweak*.{zip,nsp}

  del_runs:
    name: Prune old workflow runs
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs
        id: del-runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 7

